### ISSUE TITLE
配置文件中的ragflow生成的apikey是从哪里得到的？

### ISSUE THREAD

**Issue by wesleyanZhao** [Samge0/ragflow-upload#2]
配置文件中的ragflow生成的apikey是从哪里得到的？

**Comment by wesleyanZhao** [comment]
还有，能详细介绍下配置文档中的配置项吗？ 比如解析ID，或者知识库ID，这些ID是从哪里获取的？谢谢！

**Comment by Samge0** [comment]
好的，一会我整理一下，贴到这里

**Comment by Samge0** [comment]
首先需要在ragflow中创建一个`知识库`，然后在知识库页面按F2获取ragflow的`接口地址`、`知识库id信息`、`Authorization`信息，如下图：
![image](https://github.com/user-attachments/assets/eebd13d1-27c6-4f2a-9c5c-30a83354eb3f)

### ragflow的api地址，请替换为实际的服务器地址
F12 -> 点击`Network` -> 点击`Fetch/XHR` -> 刷新当前知识库页面-> 点击`list?kb_id`相关的页面 -> 点击`Headers` -> 在`General`的`Request URL`获取`API_URL`地址，例如：
```text
API_URL = 'http://localhost:31180/v1'
```  

### ragflow的api鉴权token
F12 -> 点击`Network` -> 点击`Fetch/XHR` -> 刷新当前知识库页面-> 点击`list?kb_id`相关的页面 -> 点击`Headers` -> 在`Request Headers`的`Authorization`获取接口的验证信息`AUTHORIZATION`，例如：
```text
AUTHORIZATION = 'IjZkY2NiNDk0NjA2YzExZWY4YTlhMDI0MmFjMTgwMDA4Ig.ZscKrA.8mbdl5qXORovVz1nvVzBrTaF3Nk'
```  

### ragflow的知识库id
F12 -> 点击`Network` -> 点击`Fetch/XHR` -> 刷新当前知识库页面-> 点击`list?kb_id`相关的页面 -> 点击`Headers` -> 在`General`的`Request URL`获取知识库的`kb_id`，例如：
```text
DIFY_DOC_KB_ID = '831499b0651311ef89c40242ac180006'
```  

### ragflow的知识库名称
这是是创建知识库时定义的知识库名称
```text
KB_NAME = "icloud-note-helper"
```  

### ragflow的知识库文档解析方式
```text
PARSER_ID = "naive"
```  
解析方式的类型可以在[官方文档](https://ragflow.io/docs/dev/api#demo-for-upload-filepython)中找到，这里也贴一份，方便查阅：
| parser_id   | 名称           | 描述                                                |
|-------------|----------------|-----------------------------------------------------|
| naive       | General         | 通用解析器，适用于没有明确格式的文本或信息。           |
| qa          | Q&A             | 处理问答型内容，解析包含问题和答案的结构化或半结构化数据。|
| manual      | Manual          | 解析手册或说明书类文档，提取指导性或技术性内容。        |
| table       | Table           | 处理表格数据，提取行列结构化信息。                    |
| paper       | Paper           | 解析学术论文或报告型文档，提取摘要、章节等内容。        |
| laws        | Laws            | 解析法律文档，提取法规、条款和法典信息。               |
| presentation| Presentation     | 处理演示文稿，提取幻灯片中的标题、内容和图表等信息。    |
| picture     | Picture         | 处理图片类数据，结合OCR等技术提取图像中的信息。        |
| one         | One             | 用于单个文件或对象的简单数据解析。                    |

![image](https://github.com/user-attachments/assets/49f4ea7e-5615-454c-8c4d-6d7f6596a235)


### 文档目录 
这里配置自己本地要上传的目录地址即可
```text
DOC_DIR = 'F:/Space/Share/111111111/mac-notes/iCloud'
```

### 指定文档后缀
需要上传的文件后缀类型
```text
DOC_SUFFIX = 'md,txt,pdf,docx'
```    

### ragflow中mysql的配置
```text
MYSQL_HOST = 'localhost'
MYSQL_PORT = 5455
MYSQL_USER = 'root'
MYSQL_PASSWORD = 'infini_rag_flow'
MYSQL_DATABASE = 'rag_flow'
```
这mysql的配置对应的是ragflow项目中`.env`文件的mysql配置，根据自己实际情况填写即可。如果是本地docker方式运行，需要映射一下该数据库端口到本机

**Comment by anthonypannn** [comment]
这是个宝藏呀，我就缺这一步了

**Comment by lin-zhenhao** [comment]
大佬您好，有一个问题想请教您，如何添加上传解析后的文件的解析块的关键词，这个关键词是存在数据库中的吗，我在数据库中没有找到关键字的存储位置

**Comment by lin-zhenhao** [comment]
> 大佬您好，有一个问题想请教您，如何添加上传解析后的文件的解析块的关键词，这个关键词是存在数据库中的吗，我在数据库中没有找到关键字的存储位置

已解决

**Comment by liberateq1** [comment]
大佬，这个只上传了但是没有解析
是什么原因

**Comment by zhaochunyang666** [comment]
如果是本地docker方式运行，如何·映射一下该数据库端口到本机，请问有没有大神能告诉我这一步怎么做，一直卡到这一步，求求大家了

**Comment by fstvhanx** [comment]
2025-08-25 16:47:59 日志已清理
2025-08-25 16:50:36 保存序号缓存失败: [Errno 22] Invalid argument: 'C:\\Users\\Administrator\\.ragflow_upload\\index_38f50ed2608011f09f957ab709b8b7f2_\nxml测试.txt'
2025-08-25 16:50:36 配置已保存
2025-08-25 16:50:36 开始运行上传程序...
2025-08-25 16:50:36 复制用户配置到包内配置: C:\Users\Administrator\.ragflow_upload\configs.py -> C:\Users\ADMINI~1\AppData\Local\Temp\_MEI336202\ragflows\configs.py
2025-08-25 16:50:36 已更新包内配置
2025-08-25 16:50:36 数据库连接已重置
2025-08-25 16:50:36 ragflow version：v0.20.1 slim
2025-08-25 16:50:36 【1/5】正在处理：D:/知识库图文召回测试/xml测试/2003-05-02/A1/output_docs/A1/2003-05-02_A1_严防死守  确保农村“绿洲”安全.docx
2025-08-25 16:50:36 运行失败: [Errno 22] Invalid argument: 'C:/Users/Administrator/.ragflow_upload/index_38f50ed2608011f09f957ab709b8b7f2_\nxml测试.txt'
2025-08-25 16:50:36 详细错误信息:
2025-08-25 16:50:36 Traceback (most recent call last):
  File "launcher.py", line 422, in run
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI336202\ragflows\main.py", line 122, in main
    fileutils.save(index_filepath, str(i+1))
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI336202\utils\fileutils.py", line 33, in save
    with open(filepath, mode, encoding='utf-8') as f:
OSError: [Errno 22] Invalid argument: 'C:/Users/Administrator/.ragflow_upload/index_38f50ed2608011f09f957ab709b8b7f2_\nxml测试.txt'

2025-08-25 16:50:36 已停止运行
请问哪里有问题呢
